apiVersion: v1
kind: Service
metadata:
  name: k8s-external-mysql
spec:
  ports:
    - port: 13306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: k8s-external-mysql
subsets:
  - addresses:
      - ip: 172.30.1.29
    ports:
      - port: 13306
