apiVersion: v1
kind: Service
metadata:
  name: k8s-external-mysql
spec:
  ports:
    - port: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: k8s-external-mysql
subsets:
  - addresses:
      - ip: 192.168.0.187
    ports:
      - port: 13306
