apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/PersonalizedNews-MSA/k8s-app-config.git
    targetRevision: HEAD
    path: k8s-api-gateway/prd

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
