apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  application-dev.yml: |
    server:
      port: 8080

    spring:
      cloud:
        gateway:
          mvc:
            routes:
              - id: favorite
                uri: http://k8s-favorite-service:8080
                predicates:
                  - Path=/api/favorite/v1/**
              - id: news-display
                uri: http://k8s-news-display-service:8080
                predicates:
                  - Path=/api/news-display/v1/**
