apiVersion: v1
kind: ConfigMap
metadata:
  name: summary-service-config
data:
  application-dev.yml: |
    server:
      port: 8080
    spring:
          ai:
            openai:
              chat:
                options:
                  model: gpt-4o 